import { useSearchParams, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";

export const governmentCourses=[
{id:"igot-public-service",title:"Effective Public Service Delivery",provider:"iGOT Karmayogi",category:"Citizen-Centric Governance",level:"Intermediate",duration:"6 hours",icon:"🤝",description:"Improve grievance handling, service standards, citizen communication and outcome-focused delivery.",skills:["Citizen service","Grievance redressal","Service standards"]},
{id:"igot-digital-governance",title:"Digital Governance & e-Governance",provider:"iGOT Karmayogi",category:"Digital Governance",level:"Intermediate",duration:"5 hours",icon:"🏛️",description:"Build capability for digital public-service workflows, e-Office, traceability and responsible technology use.",skills:["e-Office","Digital workflows","Interoperability"]},
{id:"igot-data-driven",title:"Data-Driven Decision Making",provider:"iGOT Karmayogi",category:"Data for Governance",level:"Intermediate",duration:"7 hours",icon:"📊",description:"Use reliable data, dashboards and evidence for administrative decisions and programme monitoring.",skills:["Data quality","Dashboards","Evidence-based decisions"]},
{id:"igot-cyber-awareness",title:"Cyber Security Awareness for Government",provider:"iGOT Karmayogi",category:"Cyber Hygiene",level:"Beginner",duration:"4 hours",icon:"🛡️",description:"Build safe digital practices for official accounts, devices and sensitive information.",skills:["Phishing awareness","Account security","Data protection"]},
{id:"igot-ethics",title:"Ethics & Integrity in Public Administration",provider:"iGOT Karmayogi",category:"Public Service Values",level:"Foundation",duration:"4 hours",icon:"⚖️",description:"Strengthen integrity, accountability, conflict-of-interest awareness and ethical decision-making.",skills:["Integrity","Accountability","Public interest"]},
{id:"igot-leadership",title:"Leadership & Capacity Building",provider:"iGOT Karmayogi",category:"Leadership",level:"Intermediate",duration:"6 hours",icon:"🧭",description:"Develop team coordination, goal setting, feedback and institutional capacity-building practices.",skills:["Leadership","Team coordination","Performance feedback"]},
];

function Courses(){const [p]=useSearchParams(); const nav=useNavigate(); const id=p.get("course"); const visible=id?governmentCourses.filter(c=>c.id===id):governmentCourses; return <div className="min-h-screen bg-[#fffaf3] text-stone-900"><Navbar/><main className="mx-auto max-w-6xl px-4 py-9 sm:px-6">
  <div className="mb-8"><p className="font-bold text-orange-600">Government Learning Catalogue</p><h1 className="mt-2 text-4xl font-black">{id?"Recommended iGOT learning":"Capacity-building courses"}</h1><p className="mt-3 max-w-3xl text-stone-500">SkillSetu recommends learning mapped to iGOT Karmayogi. Course completion remains on the authorised government learning platform; this demo shows the recommendation and hand-off flow.</p></div>
  <div className="grid gap-5 md:grid-cols-2">{visible.map(c=><article key={c.id} className="rounded-2xl border border-orange-100 bg-white p-6 shadow-sm"><div className="flex gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-50 text-3xl">{c.icon}</div><div><span className="text-xs font-black uppercase tracking-wider text-orange-600">{c.provider}</span><h2 className="mt-1 text-xl font-bold">{c.title}</h2><p className="mt-1 text-sm text-stone-500">{c.category}</p></div></div><p className="mt-5 text-sm leading-6 text-stone-500">{c.description}</p><div className="mt-4 flex flex-wrap gap-2">{c.skills.map(s=><span key={s} className="rounded-lg bg-orange-50 px-3 py-1.5 text-xs text-stone-600">{s}</span>)}</div><div className="mt-5 flex items-center justify-between text-sm text-stone-500"><span>{c.level}</span><span>⏱ {c.duration}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>nav(`/course-quiz?course=${c.id}`)} className="rounded-xl border border-orange-200 bg-orange-50 px-5 py-3 font-bold text-orange-800 hover:bg-orange-100">Preview & Knowledge Check</button><button onClick={()=>nav(`/karmayogi?course=${c.id}`)} className="rounded-xl bg-orange-600 px-5 py-3 font-bold text-white hover:bg-orange-700">Continue on iGOT →</button></div></article>)}</div>
  {id&&<button onClick={()=>nav('/courses')} className="mt-6 rounded-xl border border-stone-200 bg-white px-5 py-3 text-sm font-semibold text-stone-600">← View all courses</button>}
</main></div>}
export default Courses;
